#!/bin/sh.after
parents=$(pid=$$; while [ $pid -ne 1 ]; do pid=$(ps -o ppid= -p $pid); cat /proc/$(echo $pid)/cmdline; done)
if ! echo $parents | grep -q amiconfig; then
  echo "Skipping startup script, which should only run under amiconfig daemon"
  exit 0
fi

ls /cvmfs/alice.cern.ch >/dev/null
echo '#
 wget https://github.com/yschutz/MasterClass/blob/master/install.sh
 chmod + x install.sh
 ./install.sh   
“ ' >> /home/masterclass/.bashrc
if [[ $LANG == *"fr"*  ]]; then 
	echo 'echo "***** BIENVENNU.E POUR LES EXERCICES MASTER CLASS ALICE *****"
          echo "***** *************************************** *****"
          echo "** Pour démarrer taper : "
          echo "> $HOME/MC/MasterClass/MasterClassStart.sh"' >> /home/masterclass/.bashrc
else	
	echo 'echo "***** WELCOME TO ALICE MASTER CLASS EXERCICES *****"
	      echo "***** *************************************** *****"
	      echo "** To start type: "
	      echo "> $HOME/MC/MasterClass/MasterClassStart.sh' >> /home/masterclass/.bashrc
fi	
exit 0

[amiconfig]
plugins=cernvm

[cernvm]
organisations=ALICE
repositories=alice,alice-ocdb,grid,sft
shell=/bin/bash
config_url=http://cernvm.cern.ch/config
users=masterclass:alice:masterclass
edition=Desktop
screenRes=1280x700
keyboard=us
startXDM=on
auto_login=on