#!/bin/sh.after
parents=$(pid=$$; while [ $pid -ne 1 ]; do pid=$(ps -o ppid= -p $pid); cat /proc/$(echo $pid)/cmdline; done)
if ! echo $parents | grep -q amiconfig; then
  echo "Skipping startup script, which should only run under amiconfig daemon"
  exit 0
fi
[amiconfig]
plugins=cernvm

[cernvm]
organisations=ALICE
repositories=alice,alice-ocdb,grid,sft
shell=/bin/bash
config_url=http://cernvm.cern.ch/config
users=masterclass:alice:masterclass
edition=Desktop
screenRes=1280x700
keyboard=us
startXDM=on
auto_login=on